name: Publish to GH Pages
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/master'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          if sudo snap install hugo; then
            echo "Hugo installed via snap"
          else
            echo "Snap install failed, falling back to GitHub release"

            latest=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest \
              | grep browser_download_url \
              | grep extended \
              | grep Linux-64bit.tar.gz \
              | cut -d '"' -f 4)

            echo "Downloading: $latest"
            curl -L "$latest" -o hugo.tar.gz
            tar -xzf hugo.tar.gz
            sudo mv hugo /usr/local/bin/hugo
          fi

      - name: Build
        run: |
          hugo

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'PittyPaladin'
          git config user.email 'david.perez.ruiz.upc@gmail.com'
          git commit -m 'Updated site'
          git push
